# Simple Web App on Windows
# Package and deploy a simple web application on Windows web app

trigger:
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: 'vs2017-win2016'

    steps:

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: ''
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'development'
    pool:
      vmImage: 'vs2017-win2016'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'afde471e-db79-4970-b991-72c7d0b1942d'
              appType: webApp
              appName: 'cosmossampleplkt'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
